name: tap_cash
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  top_snackbar_flutter: ^3.0.0+1
  flutter_verification_code: ^1.1.6
  slide_countdown: ^0.5.0
  flutter_nfc_kit: ^3.3.1
  awesome_dialog: ^3.0.2
  image_picker: ^0.8.7+4
  image_cropper: ^3.0.3
  local_auth: ^2.1.6
  eg_nid: ^0.0.1
  flutter_credit_card: ^3.0.6
  credit_card_scanner: ^1.0.5
  font_awesome_flutter: ^10.4.0
  http: ^0.13.6
  syncfusion_flutter_charts: ^21.2.3
  dio: ^5.1.1
  intl: ^0.18.1
  mobile_scanner: ^3.2.0
  qr_flutter: ^4.0.0
  flutter_slidable: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/Icons/
    - assets/images/
    - assets/card/
    - assets/bottomNavFloat/
    - assets/bottomNav/
    - assets/home/
    - assets/bottomSheeet/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf

